### ISSUE TITLE
(error: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by jashsu** [theopolisme/location-history-visualizer#16] opened 2016-05-06 21:56 UTC
Getting this error from my takeout json. Not much to go on in the js console.

**Comment by tbolick** [comment] 2016-05-31 21:15
Same error.  Can provide file if needed.  (345MB)

**Comment by Frankster-NL** [comment] 2016-06-09 09:32
And the same here (300MB JSON file)

**Comment by theopolisme** [comment] 2016-06-09 10:27
Hi all - thanks for the reports. Yes, there is an issue with processing files over 256 MB. It has been fixed in the Pro version of the visualizer, but the fix has not yet been ported over to the free heatmap tool. The crux of the issue is in-browser memory limits for a single object (and/or hitting total RAM capacity). The fix involves steaming the JSON into memory instead for files over ~256 MB.

I anticipate having the fix live in the next month or so; at present I am abroad and sans computer which severely inhibits productivity. Thanks for your patience - I will drop another comment when the issue has been resolved.

Best,
Theo

**Comment by sandrotosi** [comment] 2016-09-11 22:27
any update on this?

**Comment by perringaiden** [comment] 2016-11-27 23:40
Got the same here.  277MB file so just over the limit.

**Comment by nardz13** [comment] 2016-12-02 04:42
same issue here.

**Comment by abhisuri97** [comment] 2016-12-04 23:12
@tbolick I am working on a fix for this, would you mind providing me with the 345 mb file so I can test? my email is suria AT seas DOT upenn DOT edu

**Comment by sammyc53** [comment] 2017-01-10 06:04
Same. I'll be happy to provide my file (~340MB). Let me know.

**Comment by justanotheramateur** [comment] 2017-07-19 01:08
As an alternative, what about allowing gzip uploads? Would that help with the upload limit at all, or does it happen after file transfer?

**Comment by theopolisme** [comment] 2017-07-19 01:21
@justanotheramateur The files are actually never uploaded to a server - all processing happens locally.

Pull request #18 resolves the issue, but fell off my radar due to school and has not yet been merged into master - I will look into getting it merged now.

**Comment by justanotheramateur** [comment] 2017-07-19 01:24
Thank you!

**Closed** 2017-07-19 01:41 UTC
